/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTransferAdmissionsRouteImport } from './routes/services.transfer-admissions'
import { Route as ServicesGraduateAdmissionsRouteImport } from './routes/services.graduate-admissions'
import { Route as ServicesBsMdProgramsRouteImport } from './routes/services.bs-md-programs'
import { Route as ServicesAthleticRecruitmentRouteImport } from './routes/services.athletic-recruitment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardUniversitiesRouteImport } from './routes/_authenticated/dashboard.universities'
import { Route as AuthenticatedDashboardSessionsRouteImport } from './routes/_authenticated/dashboard.sessions'
import { Route as AuthenticatedDashboardQuizzesRouteImport } from './routes/_authenticated/dashboard.quizzes'
import { Route as AuthenticatedDashboardProgressRouteImport } from './routes/_authenticated/dashboard.progress'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTransferAdmissionsRoute =
  ServicesTransferAdmissionsRouteImport.update({
    id: '/transfer-admissions',
    path: '/transfer-admissions',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGraduateAdmissionsRoute =
  ServicesGraduateAdmissionsRouteImport.update({
    id: '/graduate-admissions',
    path: '/graduate-admissions',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesBsMdProgramsRoute = ServicesBsMdProgramsRouteImport.update({
  id: '/bs-md-programs',
  path: '/bs-md-programs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAthleticRecruitmentRoute =
  ServicesAthleticRecruitmentRouteImport.update({
    id: '/athletic-recruitment',
    path: '/athletic-recruitment',
    getParentRoute: () => ServicesRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUniversitiesRoute =
  AuthenticatedDashboardUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSessionsRoute =
  AuthenticatedDashboardSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuizzesRoute =
  AuthenticatedDashboardQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProgressRoute =
  AuthenticatedDashboardProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/bs-md-programs': typeof ServicesBsMdProgramsRoute
  '/services/graduate-admissions': typeof ServicesGraduateAdmissionsRoute
  '/services/transfer-admissions': typeof ServicesTransferAdmissionsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/bs-md-programs': typeof ServicesBsMdProgramsRoute
  '/services/graduate-admissions': typeof ServicesGraduateAdmissionsRoute
  '/services/transfer-admissions': typeof ServicesTransferAdmissionsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/bs-md-programs': typeof ServicesBsMdProgramsRoute
  '/services/graduate-admissions': typeof ServicesGraduateAdmissionsRoute
  '/services/transfer-admissions': typeof ServicesTransferAdmissionsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/_authenticated/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/_authenticated/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/_authenticated/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/signup'
    | '/success-stories'
    | '/team'
    | '/dashboard'
    | '/services/athletic-recruitment'
    | '/services/bs-md-programs'
    | '/services/graduate-admissions'
    | '/services/transfer-admissions'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/quizzes'
    | '/dashboard/sessions'
    | '/dashboard/universities'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/signup'
    | '/success-stories'
    | '/team'
    | '/services/athletic-recruitment'
    | '/services/bs-md-programs'
    | '/services/graduate-admissions'
    | '/services/transfer-admissions'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/quizzes'
    | '/dashboard/sessions'
    | '/dashboard/universities'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/signup'
    | '/success-stories'
    | '/team'
    | '/_authenticated/dashboard'
    | '/services/athletic-recruitment'
    | '/services/bs-md-programs'
    | '/services/graduate-admissions'
    | '/services/transfer-admissions'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/progress'
    | '/_authenticated/dashboard/quizzes'
    | '/_authenticated/dashboard/sessions'
    | '/_authenticated/dashboard/universities'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/transfer-admissions': {
      id: '/services/transfer-admissions'
      path: '/transfer-admissions'
      fullPath: '/services/transfer-admissions'
      preLoaderRoute: typeof ServicesTransferAdmissionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/graduate-admissions': {
      id: '/services/graduate-admissions'
      path: '/graduate-admissions'
      fullPath: '/services/graduate-admissions'
      preLoaderRoute: typeof ServicesGraduateAdmissionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/bs-md-programs': {
      id: '/services/bs-md-programs'
      path: '/bs-md-programs'
      fullPath: '/services/bs-md-programs'
      preLoaderRoute: typeof ServicesBsMdProgramsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/athletic-recruitment': {
      id: '/services/athletic-recruitment'
      path: '/athletic-recruitment'
      fullPath: '/services/athletic-recruitment'
      preLoaderRoute: typeof ServicesAthleticRecruitmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/universities': {
      id: '/_authenticated/dashboard/universities'
      path: '/universities'
      fullPath: '/dashboard/universities'
      preLoaderRoute: typeof AuthenticatedDashboardUniversitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sessions': {
      id: '/_authenticated/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof AuthenticatedDashboardSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/quizzes': {
      id: '/_authenticated/dashboard/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof AuthenticatedDashboardQuizzesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/progress': {
      id: '/_authenticated/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof AuthenticatedDashboardProgressRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardProgressRoute: typeof AuthenticatedDashboardProgressRoute
  AuthenticatedDashboardQuizzesRoute: typeof AuthenticatedDashboardQuizzesRoute
  AuthenticatedDashboardSessionsRoute: typeof AuthenticatedDashboardSessionsRoute
  AuthenticatedDashboardUniversitiesRoute: typeof AuthenticatedDashboardUniversitiesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardProgressRoute: AuthenticatedDashboardProgressRoute,
    AuthenticatedDashboardQuizzesRoute: AuthenticatedDashboardQuizzesRoute,
    AuthenticatedDashboardSessionsRoute: AuthenticatedDashboardSessionsRoute,
    AuthenticatedDashboardUniversitiesRoute:
      AuthenticatedDashboardUniversitiesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAthleticRecruitmentRoute: typeof ServicesAthleticRecruitmentRoute
  ServicesBsMdProgramsRoute: typeof ServicesBsMdProgramsRoute
  ServicesGraduateAdmissionsRoute: typeof ServicesGraduateAdmissionsRoute
  ServicesTransferAdmissionsRoute: typeof ServicesTransferAdmissionsRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAthleticRecruitmentRoute: ServicesAthleticRecruitmentRoute,
  ServicesBsMdProgramsRoute: ServicesBsMdProgramsRoute,
  ServicesGraduateAdmissionsRoute: ServicesGraduateAdmissionsRoute,
  ServicesTransferAdmissionsRoute: ServicesTransferAdmissionsRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
